[system]
compatible=rpi0-2w
bootloader=uboot

[keyring]
path=/etc/rauc/ca.cert.pem
 
[slot.rootfs.A]
device=/dev/mmcblk0p2
type=ext4
bootname=A
 
[slot.rootfs.B]
device=/dev/mmcblk0p3
type=ext4
bootname=B

