[system]
compatible=rpi0-2w
bootloader=uboot
bundle-formats=verity

[keyring]
path=/etc/rauc/ca.cert.pem
 
[slot.rootfs.A]
device=/dev/mmcblk0p3
type=ext4
bootname=A

[slot.boot.A]
device=/dev/mmcblk0p2
type=vfat
parent=rootfs.A

 
[slot.rootfs.B]
device=/dev/mmcblk0p5
type=ext4
bootname=B

[slot.boot.B]
device=/dev/mmcblk0p1
type=vfat
parent=rootfs.B
