#custom distro for raspberrypi02w 

DISTRO = "distro-rpi"
DISTRO_NAME = "distro-rpi reference  distribution for Raspberry pi"
DISTRO_VERSION = "2025.09" 


# init manager (sysvinit or systemd )
INIT_MANAGER = "systemd"


#Use one tmp directory (this to avoid the creation of the directory (tmp-glic) 
TCLIBCAPPEND = ""


#distro features 
DISTRO_FEATURES = "\
	acl \ 
	ext2 \
	ipv4 \
	ipv6 \
	pcmcia \
	usbhost \
	wifi \
	vfat \
	seccomp \
	usrmerge \
"
#prevent the installation of all recommended packages 
NO_RECOMMENDATIONS = "1"

DISTRO_EXTRA_RDEPENDS = ""
DISTRO_EXTRA_RRECOMMENDS = ""

#specify the package manager the openembedded build system uses when packaging data 
PACKAGE_CLASSES ?= "package_ipk"

#Enhance security options for CFLAGS and LDFALGS 
require conf/distro/include/security_flags.inc

#Enable CVE checks 
INHERIT += "cve-check"
#Add this file so bitbake will execuled the irrelevant CVEs from OE-CORE(or poky).
include conf/distro/include/cve-extra-exclusions.inc

# build information 
INHERIT+= "image-buildinfo"


#rauc mechanism update 
DISTRO_FEATURES += "rauc"
